version: "2"
services:
  web:
    build:
      context: .
      dockerfile: chimera-cms.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    build:
      context: .
      dockerfile: chimera-db.dockerfile
    ports:
      - "27018:27018"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
