version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27018:27018"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
